{"name": "Отображения заказа в меню \"В работе\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <order_feed_test.TestsOrderFeed object at 0x0000024A25E18EF0>, driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"0b2cd02b-afcf-44c2-b970-9c810778dde5\")>\nuser = {'email': 'zeouptdcis@yandex.ru', 'json': {'accessToken': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTg...True, 'user': {'email': 'zeouptdcis@yandex.ru', 'name': 'zeouptdcis'}}, 'name': 'zeouptdcis', 'password': 'ymihfpdfod'}\n\n    @allure.title('Отображения заказа в меню \"В работе\"')\n    def test_displaying_order_menu_orders(self, driver, user):\n        order_feed_page = OrderFeedPage(driver)\n        order_feed_page.go_to_site(Url.LOGIN_URL)\n        personal_account_page = PersonalAccountPage(driver)\n        personal_account_page.login_to_account(user)\n        main_function_page = MainFunctionPage(driver)\n        main_function_page.add_ingredient()\n        main_function_page.click_place_order()\n>       num_order = order_feed_page.get_num_order()\n\ntests\\order_feed_test.py:75: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\order_feed_page.py:19: in get_num_order\n    self.waiting_for_the_order_number(OrderFeedLocators.NUM_ORDER, '9999')\npages\\base_page.py:41: in waiting_for_the_order_number\n    return WebDriverWait(self.driver, time).until_not(EC.text_to_be_present_in_element(locator, template))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"0b2cd02b-afcf-44c2-b970-9c810778dde5\")>, method = <function text_to_be_present_in_element.<locals>._predicate at 0x0000024A25F419E0>, message = ''\n\n    def until_not(self, method: Callable[[D], T], message: str = \"\") -> Union[T, Literal[True]]:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value evaluates to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`, or\n                  ``True`` if `method` has raised one of the ignored exceptions\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if not value:\n                    return value\n            except self._ignored_exceptions:\n                return True\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:128: TimeoutException"}, "steps": [{"name": "Вход в аккаунт", "status": "passed", "parameters": [{"name": "data", "value": "{'email': 'zeouptdcis@yandex.ru', 'name': 'zeouptdcis', 'password': 'ymihfpdfod', 'json': {'success': True, 'user': {'email': 'zeouptdcis@yandex.ru', 'name': 'zeouptdcis'}, 'accessToken': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZTg3Yjg2OWVkMjgwMDAxYjNjNDgzOSIsImlhdCI6MTcwOTczNDc5MCwiZXhwIjoxNzA5NzM1OTkwfQ.ig4aCpcpSBkbap2fGtyCwIoA4YCOxwtjw3HrbBRcZM8', 'refreshToken': 'fb26d29fa6656bc108a8f561e7c134514c2772287d2067970b0754bf3ad2f2d378b1f994accd01e3'}}"}], "start": 1709734794468, "stop": 1709734795064}, {"name": "Добавление ингредиента", "status": "passed", "start": 1709734795064, "stop": 1709734795740}, {"name": "Клик 'Оформить заказ'", "status": "passed", "start": 1709734795740, "stop": 1709734796016}, {"name": "Получить номер заказа", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"D:\\Python\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"D:\\Python\\Diplom_3\\pages\\order_feed_page.py\", line 19, in get_num_order\n    self.waiting_for_the_order_number(OrderFeedLocators.NUM_ORDER, '9999')\n  File \"D:\\Python\\Diplom_3\\pages\\base_page.py\", line 41, in waiting_for_the_order_number\n    return WebDriverWait(self.driver, time).until_not(EC.text_to_be_present_in_element(locator, template))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Python\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 128, in until_not\n    raise TimeoutException(message)\n"}, "start": 1709734796016, "stop": 1709734806480}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1709734791151, "stop": 1709734806481, "uuid": "3246a20b-a948-45b1-9ea9-209bc82b7763", "historyId": "edbbd8c174ad6ebc1afa6835f2049263", "testCaseId": "4938cd921eddeb2af2e14b749332918c", "fullName": "tests.order_feed_test.TestsOrderFeed#test_displaying_order_menu_orders", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "order_feed_test"}, {"name": "subSuite", "value": "TestsOrderFeed"}, {"name": "host", "value": "oz1"}, {"name": "thread", "value": "83604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.order_feed_test"}]}